service.port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yzm_user
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: user-thrift-service
